### ISSUE TITLE
Explain AQI in the README

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#76]

**Comment by killerninja8** [comment]
Air Quality Index (AQI) is an indicator of air quality developed by government health authorities to communicate the level of air pollution in an area. When AQI levels are high, several subgroups are affected by it's negative impacts - children, seniors, those with respiratory and cardiorespiratory illnesses. In times of high AQI, health bodies suggest people stay indoors, use high-efficiency particulate absorbing (HEPA) filters, wear NIOSH N95, and avoid any risk to their health. 

AQI is calculated as the maximum of the index of pollutant $p$, where this index is defined as: $I_p = \left\lfloor \frac{(I_{\text{high}} - I_{\text{low}}) \times (C_p - C_{\text{low}})}{(C_{\text{high}} - C_{\text{low}})} + I_{\text{low}} \right\rfloor \quad$ $\forall p \in [\{\text{CO}_2, \text{CO}, \text{O}_3, \text{PM2.5}, \text{PM10}, \text{SO}_x, \text{NO}_x\}]$. This index is the linear interpolation of concentration between concentration breakpoints ${C}$ for pollutant $p$. However, the values are often represented as one of five groups (labels vary by country): very poor, poor, moderate, good, very good. 

Needless to say, high AQI is a major problem for millions of people and health authorities. Since this easy-to-understand dashboard is intended for use by health officials, engineering an AQI feature is imperative for ensuring our public health officials are well-equipped to deal with pollution-related crises. This feature not only eliminates the need for users to convert pollutant concentration into AQI, but also saves time and prevents human conversion errors.
