### ISSUE TITLE
Consider checking if the projection is good for worldwide

### ISSUE THREAD

**Issue by meretelutz** [UBC-MDS/DSCI-532_2024_2_pollution-tracker#88]

**Comment by killerninja8** [comment]
Hi Team! I've confirmed that the Plotly default for choropleth maps is the equirectangular projection. It's commonly used because of it's simplicity, but it does not preserve angles or avoid distortions. The projection type that is the "least distorted", however, that is defined, is the "Natural Earth projection". The NE projection is designed to minimize distortion in the areas and shapes of features across the world, making it visually appealing for global maps. I've updated the maps to use natural earth. 

We can also use orthographic if we want to see a globe instead of a flat map, but angular + area distortion increase dramatically from the local to the center.
